title: DealerTech Docs
description:DealerTech Docs
theme: just-the-docs

url: https://rickomax.github.io/dealertech-docs

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
  
color_scheme: dark
